/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./scene.gltf -t -T -s
Author: berilbasak (https://sketchfab.com/berilbaska)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-toy-airplane-7de2ecbc0acb4b1886c3df3d196c366b
Title: Vintage Toy Airplane
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    BezierCircle_Material002_0: THREE.Mesh;
    BezierCircle001_Material001_0: THREE.Mesh;
    BezierCurve003_Material002_0: THREE.Mesh;
    BezierCurve004_Material002_0: THREE.Mesh;
    BezierCurve_Material002_0: THREE.Mesh;
    BezierCurve001_Material002_0: THREE.Mesh;
    BezierCurve002_Material002_0: THREE.Mesh;
    BezierCurve007_Material001_0: THREE.Mesh;
    pipe_right_Material001_0: THREE.Mesh;
    pipe_left_Material001_0: THREE.Mesh;
    wing_bottom_Material001_0: THREE.Mesh;
    wing_top_Material001_0: THREE.Mesh;
    wing_support_pannel_right_Material002_0: THREE.Mesh;
    tires_Material002_0: THREE.Mesh;
    wing_support_pannel_left_Material002_0: THREE.Mesh;
    plane_Material001_0: THREE.Mesh;
    cross_Material001_0: THREE.Mesh;
    prop_Material002_0: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshPhysicalMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

export function Airplane(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/mesh/plane.glb') as GLTFResult;
  const propellerRef = React.useRef<THREE.Mesh>(null);

  useFrame((state, delta) => {
    if (propellerRef.current) {
      propellerRef.current.rotation.z += delta * 15;
    }
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCircle_Material002_0.geometry}
          material={materials['Material.002']}
          position={[0, 336.95, -204.31]}
          rotation={[-0.22, 0, 0]}
          scale={61.74}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCircle001_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 292.76, -399.22]}
          rotation={[-0.48, 0, 0]}
          scale={53.86}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve003_Material002_0.geometry}
          material={materials['Material.002']}
          position={[27.06, 282.52, -476.22]}
          rotation={[-2.64, 0.16, 1.43]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve004_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-47.11, 280.18, -472.54]}
          rotation={[-2.64, -0.15, 1.7]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve_Material002_0.geometry}
          material={materials['Material.002']}
          position={[69.31, 159.53, -1039.4]}
          rotation={[-1.79, 0.86, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve001_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-72.28, 160.35, -1035.81]}
          rotation={[-1.79, -0.86, -Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-3.29, 269.4, -554.78]}
          rotation={[-0.93, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve007_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-0.3, 70.8, -801.14]}
          rotation={[-1.54, 0, -Math.PI / 2]}
          scale={25.6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pipe_right_Material001_0.geometry}
          material={materials['Material.001']}
          position={[88.45, 292.99, -211.42]}
          rotation={[-1.99, -0.08, 1.64]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pipe_left_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-91.03, 292.99, -211.42]}
          rotation={[-1.99, 0.08, -1.64]}
          scale={[-100, 100, 100]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wing_bottom_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 189.61, -205.19]}
          rotation={[-1.79, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wing_top_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 401.6, -256.98]}
          rotation={[-1.79, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wing_support_pannel_right_Material002_0.geometry}
          material={materials['Material.002']}
          position={[258.02, 203.78, -205.62]}
          rotation={[-0.22, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tires_Material002_0.geometry}
          material={materials['Material.002']}
          position={[145.97, 64.67, -64.23]}
          rotation={[-1.79, Math.PI / 2, 0]}
          scale={[65.01, 65.01, 17.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wing_support_pannel_left_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-262.96, 203.78, -205.62]}
          rotation={[-0.22, -Math.PI / 2, 0]}
          scale={[-100, 100, 100]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plane_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0, 300.62, -18.14]}
          rotation={[2.92, 0, Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cross_Material001_0.geometry}
          material={materials['Material.001']}
          position={[396.61, 403.34, -257.57]}
          rotation={[-1.79, 0, 0]}
          scale={86.53}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.prop_Material002_0.geometry}
          material={materials['Material.002']}
          position={[0, 300.62, -18.14]}
          rotation={[2.92, 0, Math.PI / 2]}
          scale={100}
          ref={propellerRef}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/assets/mesh/plane.glb');
