/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./src/assets/mesh/boy/scene.gltf -t -T -o ./src/components/Mesh/Boy/boy.gltf
Author: Jonás (https://sketchfab.com/jonasaguilar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viernes-8ce82f26e9f346379fe854bb0bbfa227
Title: Viernes
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type ActionName = 'Spooky';
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.SkinnedMesh;
    Object_7: THREE.SkinnedMesh;
    Object_9: THREE.SkinnedMesh;
    Object_10: THREE.SkinnedMesh;
    Object_12: THREE.SkinnedMesh;
    Object_13: THREE.SkinnedMesh;
    Object_14: THREE.SkinnedMesh;
    Object_15: THREE.SkinnedMesh;
    Object_16: THREE.SkinnedMesh;
    Object_17: THREE.SkinnedMesh;
    Object_18: THREE.SkinnedMesh;
    Object_19: THREE.SkinnedMesh;
    Object_20: THREE.SkinnedMesh;
    Object_21: THREE.SkinnedMesh;
    Object_22: THREE.SkinnedMesh;
    Object_23: THREE.SkinnedMesh;
    Object_24: THREE.SkinnedMesh;
    Object_26: THREE.SkinnedMesh;
    Object_28: THREE.SkinnedMesh;
    Object_30: THREE.SkinnedMesh;
    Object_32: THREE.SkinnedMesh;
    Object_34: THREE.SkinnedMesh;
    Object_36: THREE.SkinnedMesh;
    Object_38: THREE.SkinnedMesh;
    Object_40: THREE.SkinnedMesh;
    Object_41: THREE.SkinnedMesh;
    Object_42: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    carne: THREE.MeshBasicMaterial;
    ojos: THREE.MeshBasicMaterial;
    negro: THREE.MeshBasicMaterial;
    boca: THREE.MeshBasicMaterial;
    piernas: THREE.MeshBasicMaterial;
    brazos: THREE.MeshBasicMaterial;
  };
  animation: GLTFAction[];
};

export function Boy(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    '/assets/mesh/boy.glb'
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  React.useEffect(() => {
    actions['Spooky']?.setEffectiveTimeScale(1);
    actions['Spooky']?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name='a1667632e7224fa1b98350e3231e5f03fbx'
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name='Object_2'>
              <group name='RootNode'>
                <group name='Object_4'>
                  <primitive object={nodes._rootJoint} />
                  <group name='general'>
                    <group name='ctrl_foot_l' position={[2.27, 0.45, -4.26]}>
                      <group
                        name='puntillas'
                        position={[0, -0.23, 3.01]}
                        rotation={[0.06, 0, 0]}
                      >
                        <group name='punta' position={[0, 0, -2.15]} />
                        <group
                          name='talon'
                          position={[0, 0, -2.15]}
                          rotation={[0.94, 0, 0]}
                        />
                      </group>
                    </group>
                    <group
                      name='ctrl_foot_r'
                      position={[-2.27, 4.1, -0.15]}
                      rotation={[0.94, 0, 0]}
                    >
                      <group name='puntillas_1' position={[0, -0.23, 3.01]}>
                        <group name='talon_1' position={[0, 0, -2.15]} />
                        <group name='punta_1' position={[0, 0, -2.15]} />
                      </group>
                    </group>
                    <group
                      name='ctrl_root'
                      position={[0, 11.37, 1]}
                      rotation={[0, -0.03, 0.07]}
                    >
                      <group
                        name='ctrl_shoulder_l'
                        position={[8.81, 1.19, 1.41]}
                        rotation={[Math.PI / 2, 0.04, 0]}
                        scale={-1}
                      >
                        <group
                          name='ctrl_elbow_l'
                          position={[-5.51, 0, -0.04]}
                          rotation={[0, 0.7, 0]}
                        />
                      </group>
                      <group
                        name='ctrl_shoulder_r'
                        position={[-8.81, 1.19, 1.41]}
                        rotation={[-Math.PI / 2, -0.15, 0]}
                      >
                        <group
                          name='ctrl_elbow_r'
                          position={[-5.51, 0, -0.04]}
                          rotation={[0, 1.04, 0]}
                        />
                      </group>
                    </group>
                  </group>
                  <skinnedMesh
                    name='Object_6'
                    geometry={nodes.Object_6.geometry}
                    material={materials.carne}
                    skeleton={nodes.Object_6.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_7'
                    geometry={nodes.Object_7.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_7.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_9'
                    geometry={nodes.Object_9.geometry}
                    material={materials.negro}
                    skeleton={nodes.Object_9.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_10'
                    geometry={nodes.Object_10.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_10.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_12'
                    geometry={nodes.Object_12.geometry}
                    material={materials.negro}
                    skeleton={nodes.Object_12.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_13'
                    geometry={nodes.Object_13.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_13.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_14'
                    geometry={nodes.Object_14.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_14.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_15'
                    geometry={nodes.Object_15.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_15.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_16'
                    geometry={nodes.Object_16.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_16.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_17'
                    geometry={nodes.Object_17.geometry}
                    material={materials.negro}
                    skeleton={nodes.Object_17.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_18'
                    geometry={nodes.Object_18.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_18.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_19'
                    geometry={nodes.Object_19.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_19.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_20'
                    geometry={nodes.Object_20.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_20.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_21'
                    geometry={nodes.Object_21.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_21.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_22'
                    geometry={nodes.Object_22.geometry}
                    material={materials.boca}
                    skeleton={nodes.Object_22.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_23'
                    geometry={nodes.Object_23.geometry}
                    material={materials.negro}
                    skeleton={nodes.Object_23.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_24'
                    geometry={nodes.Object_24.geometry}
                    material={materials.carne}
                    skeleton={nodes.Object_24.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_26'
                    geometry={nodes.Object_26.geometry}
                    material={materials.piernas}
                    skeleton={nodes.Object_26.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_28'
                    geometry={nodes.Object_28.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_28.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_30'
                    geometry={nodes.Object_30.geometry}
                    material={materials.brazos}
                    skeleton={nodes.Object_30.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_32'
                    geometry={nodes.Object_32.geometry}
                    material={materials.piernas}
                    skeleton={nodes.Object_32.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_34'
                    geometry={nodes.Object_34.geometry}
                    material={materials.ojos}
                    skeleton={nodes.Object_34.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_36'
                    geometry={nodes.Object_36.geometry}
                    material={materials.brazos}
                    skeleton={nodes.Object_36.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_38'
                    geometry={nodes.Object_38.geometry}
                    material={materials.carne}
                    skeleton={nodes.Object_38.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_40'
                    geometry={nodes.Object_40.geometry}
                    material={materials.carne}
                    skeleton={nodes.Object_40.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_41'
                    geometry={nodes.Object_41.geometry}
                    material={materials.negro}
                    skeleton={nodes.Object_41.skeleton}
                    castShadow
                    receiveShadow
                  />
                  <skinnedMesh
                    name='Object_42'
                    geometry={nodes.Object_42.geometry}
                    material={materials.negro}
                    skeleton={nodes.Object_42.skeleton}
                    castShadow
                    receiveShadow
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/assets/mesh/boy.glb');
